### PR TITLE
Feature/kafka auth via sasl

### PR DESCRIPTION
**Pull request by haidlir**
1. Kafka enables the producer/consumer to use SASL authentication method using JAAS. The producer/sarama.go has been modifed to enable the vflow's sarama-producer to pass SASL username and password to kafka.

2. It is possible to create a small sized docker image using alpine by placing only the compiled binary file into the container image. The size of the image was shrunk from 621MB to 19.3 MB

### CODE REVIEW

**Comment by leoluk** [comment]
I suggest you split this into two PRs - one for SASL, one for the build system, such that they can be discussed separately.

SASL change LGTM.

**Comment by mehrdadrad** [comment]
@haidlir could you please send the SASL part only?

**Comment by haidlir** [comment]
Hi @mehrdadrad 
Recently, I updated the branch and only PR the SASL commit..

**Comment by mehrdadrad** [comment]
@haidlir thanks!

**Pull request merged**
