### PR TITLE
fix Ipfix OOM

### PR DESCRIPTION
**Pull request by glowa001**
out of memory in decodeSet()
#97

### CODE REVIEW

**Comment by avimas** [comment]
The issue appears also in V9, this fix is very partial and it deals only with the symptoms and not with the root cause, the router didn't send 0 as a set id number,  this set id number is a consequence of a wrong template caching causing wrong parsing.

a complete fix (also handles the case of malicious packet with 0 as set id) can be found at:
https://github.com/alexeigr/vflow 

I am not sure how this fix affect the template rpc mechanism (which isn't used in my environment) though .

**Comment by glowa001** [comment]
I can't agree with you. 

First of all, your fix still wrong decode the packet correctly decoded by wireshark (and my fix showed in issue description). Please run my sample code and compare the output.

In fact, my fix deals only with IPFIX beacause I work only with IPFIX and I can't test it on other protocols. And in fact,  router didn't send 0 as a set id but this is not a problem (in my sample code is full payload of templates and data).

Do you append unknown elements to decoded fields as octetArray without any warring? This is not good idea in my opinion.

However, thanks for your comment.

**Comment by avimas** [comment]
Thanks for your comment could you upload a complete pcap so I can see whats wrong?
The cache logic implemented by  vflow is wrong and it caused us many problem, the suggested fix deals with this issue.

Yes I append unknown elements as an octet array because I only need 5 known fields from the the flow, and I don't want to loose this information because of an unknown element, I know this is very specific that is why I didn't ask for a pull request.

**Comment by glowa001** [comment]
File that you asked for:
[oom_vflow_edit.zip](https://github.com/VerizonDigital/vflow/files/3017186/oom_vflow_edit.zip)

I repeat myself, but for the sake of clarity

Wireshark decode (correct):
```
Cisco NetFlow/IPFIX
    Version: 10
    Length: 288
    Timestamp: Feb  4, 2019 14:27:04.000000000 CET
    FlowSequence: 95526 (expected 95510)
    Observation Domain Id: 0
    Set 1 [id=1024] (2 flows)
        FlowSet Id: (Data) (1024)
        FlowSet Length: 120
        [Template Frame: 1]
        Flow 1
            [Duration: 1.816000000 seconds (milliseconds)]
            Octets: 840
            Packets: 10
            IPVersion: 4
            InputInt: 0
            OutputInt: 0
            Direction: Ingress (0)
            SrcAddr: 10.0.2.15
            DstAddr: 216.58.215.99
            SrcPort: 0
            DstPort: 0
            IP ToS: 0x00
            TCP Flags: 0x00
            Protocol: ICMP (1)
        Flow 2
            [Duration: 1.816000000 seconds (milliseconds)]
            Octets: 840
            Packets: 10
            IPVersion: 4
            InputInt: 0
            OutputInt: 0
            Direction: Ingress (0)
            SrcAddr: 216.58.215.99
            DstAddr: 10.0.2.15
            SrcPort: 0
            DstPort: 0
            IP ToS: 0x00
            TCP Flags: 0x00
            Protocol: ICMP (1)
        Padding: 0000
    Set 2 [id=2048] (1 flows)
        FlowSet Id: (Data) (2048)
        FlowSet Length: 88
        [Template Frame: 1]
        Flow 1
            [Duration: 0.000000000 seconds (milliseconds)]
            Octets: 189
            Packets: 1
            IPVersion: 6
            InputInt: 0
            OutputInt: 0
            Direction: Ingress (0)
            SrcAddr: fe80::1f0c:7220:b25e:ccbd
            DstAddr: ff02::fb
            IP ToS: 0x00
            SrcPort: 5353
            DstPort: 5353
            TCP Flags: 0x00
            Protocol: UDP (17)
        Padding: 000000
    Set 3 [id=1024] (1 flows)
        FlowSet Id: (Data) (1024)
        FlowSet Length: 64
        [Template Frame: 1]
        Flow 1
            [Duration: 0.000000000 seconds (milliseconds)]
            Octets: 169
            Packets: 1
            IPVersion: 4
            InputInt: 0
            OutputInt: 0
            Direction: Ingress (0)
            SrcAddr: 10.0.2.15
            DstAddr: 224.0.0.251
            SrcPort: 5353
            DstPort: 5353
            IP ToS: 0x00
            TCP Flags: 0x00
            Protocol: UDP (17)
        Padding: 000000
    [Expected Sequence Number: 95510]
    [Previous Frame in Sequence: 1]
```

Decoding output with my fix (same as wireshark - correct): 
````{"AgentID":"127.0.0.1","Header":
{"Version":10,"Length":288,"ExportTime":1549286824,"SequenceNo":95526,"DomainID":0},"DataSets":
[[{"I":153,"V":1549286824585},{"I":152,"V":1549286822769},{"I":1,"V":840},{"I":2,"V":10},{"I":60,"V":4},{"I":10,"V":0},{"I":14,"V":0},{"I":61,"V":0},{"I":8,"V":"10.0.2.15"},{"I":12,"V":"216.58.215.99"},{"I":7,"V":0},{"I":11,"V":0},{"I":5,"V":0},{"I":6,"V":"0x00"},{"I":4,"V":1}],
[{"I":153,"V":1549286824585},{"I":152,"V":1549286822769},{"I":1,"V":840},{"I":2,"V":10},{"I":60,"V":4},{"I":10,"V":0},{"I":14,"V":0},{"I":61,"V":0},{"I":8,"V":"216.58.215.99"},{"I":12,"V":"10.0.2.15"},{"I":7,"V":0},{"I":11,"V":0},{"I":5,"V":0},{"I":6,"V":"0x00"},{"I":4,"V":1}],
[{"I":153,"V":1549286522610},{"I":152,"V":1549286522610},{"I":1,"V":189},{"I":2,"V":1},{"I":60,"V":6},{"I":10,"V":0},{"I":14,"V":0},{"I":61,"V":0},{"I":27,"V":"fe80::1f0c:7220:b25e:ccbd"},{"I":28,"V":"ff02::fb"},{"I":5,"V":0},{"I":7,"V":5353},{"I":11,"V":5353},{"I":6,"V":"0x00"},{"I":4,"V":17}],
[{"I":153,"V":1549286522610},{"I":152,"V":1549286522610},{"I":1,"V":169},{"I":2,"V":1},{"I":60,"V":4},{"I":10,"V":0},{"I":14,"V":0},{"I":61,"V":0},{"I":8,"V":"10.0.2.15"},{"I":12,"V":"224.0.0.251"},{"I":7,"V":5353},{"I":11,"V":5353},{"I":5,"V":0},{"I":6,"V":"0x00"},{"I":4,"V":17}]]}
````
Decoding output with your fix (incorrect):
```
IPFIX decoding error:  Multiple errors:
- can not read the data
- can not read the data
- can not read the data
- unexpected EOF
- unexpected EOF
- unexpected EOF
- can not read the data
- can not read the data
- unexpected EOF
- unexpected EOF
- unexpected EOF
- can not read the data
- unexpected EOF
- can not read the data
- unexpected EOF
- unexpected EOF
- unexpected EOF
- unexpected EOF
- unexpected EOF
- unexpected EOF
- can not read the data
- can not read the data
{"AgentID":"127.0.0.1","Header":
{"Version":10,"Length":288,"ExportTime":1549286824,"SequenceNo":95526,"DomainID":0},"DataSets":
[[{"I":153,"V":1549286824585},{"I":152,"V":1549286822769},{"I":1,"V":840},{"I":2,"V":10},{"I":60,"V":4},{"I":10,"V":0},{"I":14,"V":0},{"I":61,"V":0},{"I":8,"V":"10.0.2.15"},{"I":12,"V":"216.58.215.99"},{"I":7,"V":0},{"I":11,"V":0},{"I":5,"V":0},{"I":6,"V":"0x00"},{"I":4,"V":1}],
[{"I":153,"V":1549286824585},{"I":152,"V":1549286822769},{"I":1,"V":840},{"I":2,"V":10},{"I":60,"V":4},{"I":10,"V":0},{"I":14,"V":0},{"I":61,"V":0},{"I":8,"V":"216.58.215.99"},{"I":12,"V":"10.0.2.15"},{"I":7,"V":0},{"I":11,"V":0},{"I":5,"V":0},{"I":6,"V":"0x00"},{"I":4,"V":1}],
[{"I":153,"V":8796098789376},{"I":152,"V":101534041545768960},{"I":1,"V":101534041545768960},{"I":2,"V":12386304},{"I":60,"V":0},{"I":10,"V":0},{"I":14,"V":17170432},{"I":61,"V":0},{"I":8,"V":"0.0.0.0"},{"I":12,"V":"0.0.254.128"},{"I":7,"V":0},{"I":11,"V":0},{"I":5,"V":0},{"I":6,"V":"0x00"},{"I":4,"V":31}]]}
```

Decoding output with Vflow (oom):
```
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x8b3d2d, 0x16)
        /usr/lib/go-1.10/src/runtime/panic.go:616 +0x81
runtime.sysMap(0xc54b8d0000, 0x8fa60000, 0x0, 0x12af6d8)
        /usr/lib/go-1.10/src/runtime/mem_linux.go:216 +0x20a
runtime.(*mheap).sysAlloc(0xd7db40, 0x8fa60000, 0x0)
        /usr/lib/go-1.10/src/runtime/malloc.go:470 +0xd4
runtime.(*mheap).grow(0xd7db40, 0x47d2b, 0x0)
        /usr/lib/go-1.10/src/runtime/mheap.go:907 +0x60
runtime.(*mheap).allocSpanLocked(0xd7db40, 0x47d2b, 0x12af6e8, 0xc400000000)
        /usr/lib/go-1.10/src/runtime/mheap.go:820 +0x301
runtime.(*mheap).alloc_m(0xd7db40, 0x47d2b, 0xc420480100, 0x200000001)
        /usr/lib/go-1.10/src/runtime/mheap.go:686 +0x118
runtime.(*mheap).alloc.func1()
        /usr/lib/go-1.10/src/runtime/mheap.go:753 +0x4d
runtime.(*mheap).alloc(0xd7db40, 0x47d2b, 0x10100, 0xc420000180)
        /usr/lib/go-1.10/src/runtime/mheap.go:752 +0x8a
runtime.largeAlloc(0x8fa56000, 0xc420020001, 0xd61301)
        /usr/lib/go-1.10/src/runtime/malloc.go:826 +0x94
runtime.mallocgc.func1()
        /usr/lib/go-1.10/src/runtime/malloc.go:721 +0x46
runtime.systemstack(0x0)
        /usr/lib/go-1.10/src/runtime/asm_amd64.s:409 +0x79
runtime.mstart()
        /usr/lib/go-1.10/src/runtime/proc.go:1175

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/lib/go-1.10/src/runtime/asm_amd64.s:363 fp=0xc420063898 sp=0xc420063890 pc=0x455d80
runtime.mallocgc(0x8fa56000, 0x7e16e0, 0xc420063901, 0x1)
        /usr/lib/go-1.10/src/runtime/malloc.go:720 +0x8a2 fp=0xc420063938 sp=0xc420063898 pc=0x4139b2
runtime.growslice(0x7e16e0, 0xc469d54000, 0x4c9c6aa, 0x4c9c6aa, 0x4c9c6ab, 0x0, 0x0, 0x0)
        /usr/lib/go-1.10/src/runtime/slice.go:179 +0x14a fp=0xc4200639a0 sp=0xc420063938 pc=0x44246a
github.com/VerizonDigital/vflow/ipfix.(*Decoder).decodeSet(0xc420063c98, 0xc420150100, 0x20, 0x20, 0xc42006c140, 0x900c01, 0xc42008a040)
        /home/glowa/go/src/github.com/VerizonDigital/vflow/ipfix/decoder.go:814 +0x4af fp=0xc420063ba0 sp=0xc4200639a0 pc=0x6e995f
github.com/VerizonDigital/vflow/ipfix.(*Decoder).Decode(0xc420063c98, 0xc420150100, 0x20, 0x20, 0x8, 0x4, 0x0)
        /home/glowa/go/src/github.com/VerizonDigital/vflow/ipfix/decoder.go:728 +0x157 fp=0xc420063c28 sp=0xc420063ba0 pc=0x6e92c7
main.decode(0xc42009ec74, 0x4, 0x4, 0xc4200c09ca, 0x120, 0x120, 0xc420150100, 0x20, 0x20)
        /home/glowa/***/vflow/vflow/ipfix.go:100 +0xe4 fp=0xc420063ce8 sp=0xc420063c28 pc=0x79f2e4
main.main()
        /home/glowa/***/vflow/vflow/ipfix.go:151 +0x67b fp=0xc420063f88 sp=0xc420063ce8 pc=0x79fb4b
runtime.main()
        /usr/lib/go-1.10/src/runtime/proc.go:198 +0x212 fp=0xc420063fe0 sp=0xc420063f88 pc=0x42e552
runtime.goexit()
        /usr/lib/go-1.10/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420063fe8 sp=0xc420063fe0 pc=0x4588f1

goroutine 20 [syscall]:
github.com/google/gopacket/pcap._Cfunc_pcap_wait(0x24877e0, 0xf41dc, 0x0)
        _cgo_gotypes.go:873 +0x4d
github.com/google/gopacket/pcap.(*Handle).waitForPacket.func1(0x24877e0, 0xc4000f41dc, 0x0)
        /home/glowa/go/src/github.com/google/gopacket/pcap/pcap_unix.go:693 +0x5e
github.com/google/gopacket/pcap.(*Handle).waitForPacket(0xc42012c420)
        /home/glowa/go/src/github.com/google/gopacket/pcap/pcap_unix.go:693 +0x78
github.com/google/gopacket/pcap.(*Handle).getNextBufPtrLocked(0xc42012c420, 0xc42005fe60, 0x901ac0, 0x12aa2a0)
        /home/glowa/go/src/github.com/google/gopacket/pcap/pcap.go:330 +0x40
github.com/google/gopacket/pcap.(*Handle).ReadPacketData(0xc42012c420, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/glowa/go/src/github.com/google/gopacket/pcap/pcap.go:245 +0x84
github.com/google/gopacket.(*PacketSource).NextPacket(0xc42018b260, 0x0, 0x0, 0x901ac0, 0x12aa2a0)
        /home/glowa/go/src/github.com/google/gopacket/packet.go:800 +0x7a
github.com/google/gopacket.(*PacketSource).packetsToChannel(0xc42018b260)
        /home/glowa/go/src/github.com/google/gopacket/packet.go:817 +0x5d
created by github.com/google/gopacket.(*PacketSource).Packets
        /home/glowa/go/src/github.com/google/gopacket/packet.go:840 +0x99
exit status 2
```

What I want to get is the correctness of IPFIX decoding without runtime errors. My fix deals with only this.

**Comment by avimas** [comment]
Thanks for the info

**Comment by mehrdadrad** [comment]
@glowa001 thank you for the debugging / pull request and sorry for the delay response.

**Pull request merged**
