### PR TITLE
Swap sarama for segmentio kafka library

### PR DESCRIPTION
**Pull request by awillis**
The kafka library from segmentio provides the same kafka connectivity capability in a smaller package size. According to the authors it should also use less memory. Also included is functionality to support the use of a bootstrap server ( a dns record that points to available brokers ).

### CODE REVIEW

**Comment by mehrdadrad** [comment]
@awillis thank for your pull request.
I think it's better to have Sarama and Segmentio together at vFlow then as option, user can select one of them. can we have this changes as new producer (kafka2)? 
Already we have these options: kafka, nats, nsq, rawSocket then we will add kafka2 w/ Segmentio library.

**Comment by awillis** [comment]
@mehrdadrad Ok, I'll work on providing this as an option alongside sarama.

**Comment by awillis** [comment]
@leoluk I'm using this for a project at work currently. While we want to have some consistency in the kafka library used across several projects internally, it is in our interest to ensure that our changes can be maintained upstream as well.

**Comment by awillis** [comment]
@mehrdadrad After thinking about this a bit more, what would you say to a broader change where all producers are go plugins (https://golang.org/pkg/plugin) with a common configuration, initialization, and send message functionality?

**Comment by leoluk** [comment]
It looks like Segmentio's Kafka library has a much nicer/modern API design, with a number of projects switching to it from Sarama. How about doing a series of benchmarks to evaluate performance and memory usage? Better performance would provide a strong incentive to include it in vflow. Happy to contribute some resources to this.

I'm slightly worried about regressions for enterprise setups with outdated Kafka deployments, though. Do people use vflow with Kafka versions <0.10? It looks like Segmentio did not implement support for brokers <0.10, which sarama supports. In fact, I carry a custom patch on top of vflow to enable 0.10 support in order to get timestamps:

https://github.com/leoluk/vflow/commit/8be756577fa1e1e8fb964a127f29f1e7f5b48752

**Comment by mehrdadrad** [comment]
@awillis I like Go Plugin but it supports only Linux and MacOS

**Comment by awillis** [comment]
@mehrdadrad I see. I don't mind providing a segmentio option alongside sarama, however this task carries less priority for me at the moment. Our current need has been met with the changes that we've made on our fork.

**Comment by awillis** [comment]
Closing in favor of #85

**Pull request closed without merging**
