### PR TITLE
Issue#40: Added a new Kafka config for the sarama.MaxRequestSize

### PR DESCRIPTION
**Pull request by JPercivall**
Also added a .gitignore to ignore common Intelij files and a couple directories that are created during the build.

### CODE REVIEW

**Comment by JPercivall** [comment]
@mehrdadrad any ideas why the `make build` is failing? Doesn't seem to provide any feedback

**Comment by mehrdadrad** [comment]
@JPercivall I think that's related to recent travis-ci changes. I'll follow it up
In meanwhile can you add env variable for the new config like REQUEST_SIZE_MAX instead of NA and update doc as well. Thanks
```
RequestSizeMax  int32    `yaml:"request-size-max" env:"NA"`
```

**Comment by JPercivall** [comment]
@mehrdadrad I noticed you merged this. Sorry for not getting to the env variable, was busy with the holidays. Regardless, thanks for the review! Please let me know if there's anything needed for #46.

**Comment by mehrdadrad** [comment]
@JPercivall happy new year! and no problem
I'll review #46 soon and let you know if needed.

**Comment by JPercivall** [comment]
Fantastic and happy new year to you too!

**Pull request merged**
